config/routes.rb
Rails.application.routes.draw do
  # get 'activities/new'
  # get 'activities/create'
  # get 'activities/edit'
  # get 'activities/update'
  # get 'activities/save'
  # get 'activities/destroy'
  # get 'steps/new'
  # get 'steps/create'
  # get 'steps/edit'
  # get 'steps/save'
  # get 'steps/update'
  # get 'steps/destroy'

  devise_for :users
  root to: 'trips#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # resources trips:

    # resources :users, only: [ :show, :update ], param: :username
    get '/mytrips', to: 'pages#mytrips'
    get '/:username', to: 'users#show', as: :username
    post '/users/edit', to: 'users#update'

    resources :users, only: [ :update ]
    resources :trips do
      resources :steps, only: [ :new, :create, :edit, :update, :destroy ] do
        resources :activities, only: [ :new, :create, :edit, :update, :destroy ]
      end
    end
    get "profile", to: "profile#index"

    get '/testedittrip', to: 'pages#testedittrip'
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :steps, -> { order(position: :asc) }, dependent: :destroy
  has_many :activities, through: :steps

  validates :name, presence: true, length: { maximum: 100 }
  mount_uploader :photo, PhotoUploader
  # validates :start_date, presence: true
  # validates :end_date, presence: true

  def country_name
    country = ISO3166::Country[country_code]
    # country.translations[I18n.locale.to_s] || country.name
    # country.name
  end

  geocoded_by :country
  after_validation :geocode

  # after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  # GET /trips
  # GET /trips.json

  def index
    trip_days_param = params[:trip_days].to_i
    # @trips = Trip.all
    @trips = policy_scope(Trip).order(created_at: :desc)
    if params[:query].present?
      sql_query = " \
      trips.name ILIKE :query \
      OR trips.country ILIKE :query \
      OR steps.location ILIKE :query \
      "
      # @trip = Trip.where(sql_query, query: "%#{params[:query]}%")
      @trips = Trip.joins(:steps).where(sql_query, query: "%#{params[:query]}%").uniq
    else
      @trips = Trip.all
    end
    if params[:trip_days].present?
      @trips = @trips.select { |trip|
        ((trip_days_param - 3)..(trip_days_param + 3)).to_a.include?(trip.end_date.to_date - trip.start_date.to_date).to_i }
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    authorize @trip
    @activities = @trip.activities
    # @activitymarkers = @activities.map do |activity|
    #   {
    #     lat: activity.latitude,
    #     lng: activity.longitude,
    #     color: 'black', # blue ass water
    #     infoWindow: render_to_string(partial: "activity_info", locals: { activity: activity })
    #     #image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
    #   }
    # end
    @steps = @trip.steps
    # @stepmarkers = @steps.map do |step|
    #   {
    #     lat: step.latitude,
    #     lng: step.longitude,
    #     color: '#FE5665', # green from our Figma UI
    #     infoWindow: render_to_string(partial: "step_info", locals: { step: step })
    #     #image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
    #   }
    # end

    # @markers = @activitymarkers + @stepmarkers
  end

  def new
    @trip = Trip.new
    authorize @trip

    # @country = @trip.country
    # @countrymarkers = [{
    #     lat: @trip.latitude,
    #     lng: @trip.longitude,
    #     color: 'black', # blue ass water
    #     # infoWindow: render_to_string(partial: "activity_info", locals: { activity: activity })
    #     #image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
    #   }]

    # @markers = @countrymarkers

  end

  def create
    @trip = Trip.new(trip_params)
    @trip.country = @trip.country_name
    @trip.dates = params["dates"]
    @trip.start_date = params["dates"].split(" - ")[0]
    @trip.end_date = params["dates"].split(" - ")[1]
    @trip.user = current_user
    authorize @trip
    if @trip.save
      redirect_to edit_trip_path(@trip)
    else
      render 'new'
    end
  end

  def edit
    # @steps1 = @trip.steps
      #.sort_by{|step| step.position}
      # @list.sort_by{|e| e[:time_ago]}
    @step = Step.new
    @activity = Activity.new
    authorize @trip
    @activities = @trip.activities
    # @activitymarkers = @activities.map do |activity|
    #   {
    #     lat: activity.latitude,
    #     lng: activity.longitude,
    #     color: 'black', # blue ass water
    #     infoWindow: render_to_string(partial: "activity_info", locals: { activity: activity })
    #     #image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
    #   }
    # end
    @steps = @trip.steps
    # @steps = @trip.steps.geocoded # returns activities with coordinates
    # @stepmarkers = @steps.map do |step|
    #   {
    #     lat: step.latitude,
    #     lng: step.longitude,
    #     color: '#FE5665', # green from our Figma UI
    #     infoWindow: render_to_string(partial: "step_info", locals: { step: step })
    #     #image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
    #   }
    # end


    # @markers = @activitymarkers + @stepmarkers


        # infoWindow: render_to_string(partial: "country_info", locals: { country: country })

    # @markers = @activitymarkers + @stepmarkers
  end

  # POST /trips
  # POST /trips.json

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json

  def update
    params
    @step = Step.new
    @step.trip_id = @trip
    if params["dates"].present?
      @trip.dates = params["dates"]
      @trip.start_date = params["dates"].split(" - ")[0]
      @trip.end_date = params["dates"].split(" - ")[1]
    end
    @trip.country_code = params["trip"]["country_code"]
    @trip.country = @trip.country_name
    if @trip.update(trip_params)
      redirect_to edit_trip_path(@trip)
    else
      render :new
    end
  end

  def destroy
    @trip.destroy
    authorize @trip
    respond_to do |format|
      format.html { redirect_to mytrips_path, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_trip
      @trip = Trip.find(params[:id])
    end

    def trip_params
      params["trip"].permit(:name, :start_date, :end_date, :published, :country, :country_name, :country_code, :longitude, :latitude, :photo, :dates)

    end

end

    # respond_to do |format|
    #   if @trip.save
    #     format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
    #     format.json { render :show, status: :created, location: @trip }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @trip.errors, status: :unprocessable_entity }
    #   end
    # end


  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json


  # DELETE /trips/1
  # DELETE /trips/1.json

app/views/trips/_activity_info.html.erb
<h4><%= activity.name %></h4>
<p><%= activity.category %></p>
<p><%= activity.description %></p>

app/views/trips/_step_info.html.erb
<% @steps = @trip.steps %>
<% step_index = @steps.map { |step| step }.index(step) + 1 %>
<h3><%= step_index%>. <%= step.location %></h3>
<p>link_to the step</p>

app/views/trips/edit.html.erb
<div class="card-category" style="position:relative; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @trip.photo.present? ? @trip.photo : "https://images.unsplash.com/photo-1488646953014-85cb44e25828?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2466&q=80"%>)">
  <%= render 'trips/partials/tripinfo', trip: @trip %>
  <div style="position: absolute; top: 8px; right: 10px;">
    <a href="" data-toggle="modal" data-target="#exampleModal">
      <i class="far fa-edit" style="color: white"></i>
    </a>
    <%= render 'trips/partials/form', trip: @trip %>
  </div>
</div>



<div class="container">
  <div class="d-lg-flex justify-content-between">


    <div class="content-side">
      <div style="margin-top: 50px; margin-bottom: 50px">
        <% if @steps.empty? %>
        <h3>Start making your trip to <%= @trip.country %></h3>
        <% else %>
        <h3>Edit your trip to <%= @trip.country %></h3>
        <% end %>
      </div>
      <div class="content-info" style="border-left: 2px solid #ABAAAA;">
        <div>
          <i class="far fa-circle icon-start-end" style="border-top: 3px solid white"></i>Start: <%= @trip.start_date %>
        </div>
        <% @steps.each do |step| %>


        <div id="step-<%= step.id %>">
          <div class="d-lg-flex" style="margin-top: 30px; align-items: center">
            <div>
              <%= render 'steps/partials/stepinfo', trip: @trip, step: step %>
            </div>
            <div class="d-flex">
              <%= render 'steps/partials/stepedit', trip: @trip, step: step %>
              <%= render 'steps/partials/stepdelete', trip: @trip, step: step %>
            </div>
          </div>

<div class="collapse" id="collapseEditStep<%= step.id %>">
    <div class="card card-body" style="margin-left: 25px; border: 0">
      <%= render 'steps/partials/stepaddinfo', trip: @trip, step: step %>
    </div>
</div>



          <% step.activities.map do |activity| %>
          <div style="margin-top: 20px;">
            <%= render 'activities/partials/activityinfoedit', trip: @trip, step: step, activity: activity %>
          </div>

          <% end %>
          <div id="activitytypes-<%= step.id %>" style="margin-top: 20px;">
            <%= render 'activities/partials/activityadd', trip: @trip, step: step, activity: @activity %>
          </div>
        </div>
        <% end %>
        <div style="margin-top: 30px;">
          <h3><%= render 'steps/partials/stepadd', trip: @trip, step: @step %></h3>
        </div>
        <div style="margin-top: 30px;">
          <i class="far fa-circle icon-start-end" style="border-bottom: 5px solid white"></i>End: <%= @trip.end_date %>

        </div>
      </div>
    </div>


     <div class="map-side" style="margin-top: 30px">
      <div id="map"></div>
    </div>



  </div>



  <div class="container text-center">
    <% if @trip.published?  %>
    <%= simple_form_for [@trip] do |f| %>
    <%= f.hidden_field :country, value: @trip.country %>
     <%= f.hidden_field :country_code, value: @trip.country_code %>
    <%= f.hidden_field :published, value: :false %>
    <%= f.submit "Change to Draft", class: "btn btn-primary" %>
    <% end %>
    <% else %>
    <div class="d-md-flex justify-content-center mt-5 mb-5">
     <div class="mr-md-3">
       <%= link_to "Save as Draft", mytrips_path, class: "btn btn-outline-pink-primary" %>
     </div>
     <%= simple_form_for [@trip] do |f| %>
     <%= f.hidden_field :published, value: :true %>
     <%= f.hidden_field :dates, name: :dates %>
     <%= f.hidden_field :country, value: @trip.country %>
     <%= f.hidden_field :country_code, value: @trip.country_code %>

     <%= f.submit "Publish", class: "btn btn-primary mt-3 mt-md-0" %>

     <% end %>
     <% end %>
   </div>
 </div>

<script>
  function initMap() {
    var map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: <%= @trip.latitude %>, lng: <%= @trip.longitude %>},
      zoom: 5
    });
    <% @trip.steps.each do |step| %>
      var markerstep = new google.maps.Marker({
        position: {lat: <%= step.latitude %>, lng: <%= step.longitude %>},
        map: map
      })
    <% end %>
    <% activities_with_position = @trip.activities.select { |activity| activity.latitude.present? } %>
    <% activities_with_position.each do |activity| %>
      var markeractivity = new google.maps.Marker({
        position: {lat: <%= activity.latitude %>, lng: <%= activity.longitude %>},
        map: map
      })
    <% end %>
  }
</script>
</div>

<!-- <div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%#= ENV['MAPBOX_API_KEY'] %>"
  data-trip-cordinates="[<%= @trip.latitude %>, <%= @trip.longitude %>]"
  ></div> -->


  <%#= link_to 'Show', @trip %> <!-- | -->
  <%#= link_to 'Back', trips_path %>

  <!-- Trip banner -->
<!-- <div class="d-flex justify-content-between card-category">
  <div>
    <%#= render 'trips/partials/tripinfo', trip: @trip %>
  </div>
  <div>
    <%#= render 'trips/partials/tripedit', trip: @trip %>
  </div>
</div> -->

<!-- Each step of the trip -->
<%#= @steps1.map { |step| step.location } %>
<%#= @steps.map { |step| step.location } %>
<%# @steps.each do |step| %>
    <!-- <div style="padding: 20px 50px">
      <div id="step-" class="d-flex">
        <%#= render 'steps/partials/stepinfo', trip: @trip, step: step %>
        <div>
          <%#= render 'steps/partials/stepedit', trip: @trip, step: step %>
          <%#= render 'steps/partials/stepdelete', trip: @trip, step: step %>
        </div>
      </div> -->
      <%#= render 'steps/partials/stepeditcollapse', trip: @trip, step: step %>

      <!-- Each activity of a specific step -->
      <%# step.activities.map do |activity| %>
        <!-- <div class="d-flex" style="padding: 15px 0px">
          <div class="activity-info">
            <%#= render 'activities/partials/activityinfo', trip: @trip, step: step, activity: activity %>
          </div>
          <div>
            <%#= render 'activities/partials/activityedit', trip: @trip, step: step, activity: activity %>
            <%#= render 'activities/partials/activitydelete', trip: @trip, step: step, activity: activity %>
          </div>
       </div>
        <%#= render 'activities/partials/activityeditcollapse', trip: @trip, step: step, activity: activity %>
      <%# end %>

      <div id="activitytypes-" style="padding: 15px 0px">
        <%#= render 'activities/partials/activityadd', trip: @trip, step: step, activity: @activity %>
      </div>
    </div>
  <%# end %>
</div> -->


  <!-- <div style="padding: 20px 50px">
    <h3>Add new step <%#= render 'steps/partials/stepadd', trip: @trip, step: @step %></h3>
  </div>
  <div style="margin-top: 30px; margin-bottom: 30px">
      <%# if @trip.published?  %>
        <%#= simple_form_for [@trip] do |f| %>
          <%#= f.hidden_field :published, value: :false %>
          <%#= f.submit "Change to Draft", class: "btn btn-primary" %>
        <%# end %>
      <%# else %>
        <%#= simple_form_for [@trip] do |f| %>
          <%#= f.hidden_field :published, value: :true %>
          <%#= f.submit "Publish", class: "btn btn-primary" %>
        <%# end %>
      <%# end %>
      <%#= link_to "Save as Draft", mytrips_path, class: "btn btn-outline-green-primary" %>
    </div> -->

    <!-- <h2>Map</h2> -->

    <!-- SEARCH BAR -->
    <!-- <div id='geocoder' class='geocoder'></div> -->

    <!-- MAPBOX -->
<!-- <div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%#= ENV['MAPBOX_API_KEY'] %>"
></div>
</div> -->


<!-- ["Sleep", "See", "Eat", "Drink", "Comment", "Move"] -->
<!-- Modal for Editing Trip-->
<!-- <div id="activity-form-<%#= activity.id %>"></div> -->


 <!-- <div>
          <%#= link_to "Edit", edit_trip_step_activity_path(@trip, step, activity), remote: true %>
        </div> -->
<!--
        <div>
          <%#= link_to "Edit", edit_trip_step_path(@trip, step), remote: true %>
        </div> -->
        <!-- Comment Move Sleep See Eat Drink -->
        <!-- if click on activity.category == "comment" -->

<!-- <a class="btn btn-primary" data-toggle="collapse" href="#collapseComment" role="button" aria-expanded="false" aria-controls="collapseComment">
          Comment </a>
      <a class="btn btn-primary" data-toggle="collapse" href="#collapseSleep" role="button" aria-expanded="false" aria-controls="collapseSleep">
          Sleep </a>
      <div class="collapse" id="collapseComment">
        <div class="card card-body">
          <%#= render 'activities/partials/formcomment', trip: @trip, step: step, activity: @activity %>
        </div>
      </div>
      <div class="collapse" id="collapseComment">
        <div class="card card-body">
          <%#= render 'activities/partials/formsleep', trip: @trip, step: step, activity: @activity %>
        </div>
      </div>
    </div> -->

<!--
<script>
  document.getElementById("multiCollapseComment").addEventListener("click", (event) => {
    event.preventDefault();
    console.log(event);
    // @activity.category = "Comment";
  })

  document.getElementById("multiCollapseSleep").addEventListener("click", (event) => {
    event.preventDefault();
    console.log(event);
    // @activity.category = "Sleep";
  })
</script> -->

<!-- <script>
  var $accordion = $('#accordion');
  $accordion.on('show.bs.collapse','.collapse', function() {
  $accordion.find('.collapse.show').collapse('hide');
  });
</script> -->

<!-- if click on activity.category == "comment" -->
<!-- if click on activity.category == "sleep" -->
<%#= render 'activities/partials/formsleep', trip: @trip, step: @step %>

<!--  <%#= render 'steps/partials/form', trip: @trip, step: step %> -->



    <!-- <div class="map-side" style="margin-top: 50px;">
      <div
      id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%#= ENV['MAPBOX_API_KEY'] %>"
      data-trip-cordinates="[<%= @trip.latitude %>, <%= @trip.longitude %>]"
      ></div>
    </div> -->

app/views/trips/index.html.erb
<% content_for :nav, render('shared/navbar') %>

<div class="banner">

  <div class="col-12">
    <h1 class="mb-3">Find and share travel experiences</h1>
  </div>
  <div class="row justify-content-center">
    <button id="find-trip-button" type="button" class="btn btn-primary btn-lg mr-4 mt-4">Find a trip</button>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-outline-primary btn-lg mt-4" data-toggle="modal" data-target="#exampleModal">
      Add a trip
    </button>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Add a trip!</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <% @trip = Trip.new %>
            <%= render "trips/partials/form", trip: @trip %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="index-search-header" class="container" style="min-height: 1000px">
  <div class="row">
    <div class="col-12 mt-3" align="center">
      <h2 class="p-3 mt-5">Find travel experiences</h2>
    </div>
  </div>
  <div class="row justify-content-center p-3">

    <%= form_tag trips_path, method: :get, remote: true do %>
    <div class="search d-flex">
      <div>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control input-mysize",
          placeholder: "Location"
          %>
        </div>
        <div class= "ml-3 mr-3">
         <%= text_field_tag :trip_days,
         params[:trip_days],
         class: "form-control input-mysize",
          placeholder: "Approx. How many days?" %>
        </div>
        <div id= "search-home">
          <%= submit_tag "Search", id:"home-search-button", class: "something btn btn-primary btn-block" %>
        </div>
      </div>
      <% end %>
    </div>


    <div class="container">
      <div id="card-trip-row" class="row mt-3">
        <%= render "trips/partials/cardtrip", trip: @trip %>

      </div>
    </div>
  </div>

app/views/trips/index.js.erb
function searchTrips(innerHTML) {
  const newTripForm = document.getElementById('card-trip-row');
  newTripForm.innerHTML = innerHTML;
}

searchTrips('<%= j render "trips/partials/cardtrip", trip: @trip %>');

var elements =  document.querySelectorAll('.card-trip');
elements.forEach(element => {
element.classList.add('animated', 'fadeIn');
});


//in JS
// Grab the comntainer element
// append to the container the list of items

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'trips/partials/form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @trip.photo.present? ? @trip.photo : "https://images.unsplash.com/photo-1488646953014-85cb44e25828?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2466&q=80"%>)">
    <%= render 'trips/partials/tripinfo', trip: @trip %>
  </div>

  <div id="card-trip-user-show" class="text-center">
    <% @user = @trip.user %>
    <%= link_to username_path(@user) do %>
    <%# @user = current_user %>
    <% if @user.photo.present? %>
    <%= cl_image_tag @user.photo, crop: :thumb, gravity: :face, class: "avatar-large-bordered" %>
    <% else %>
    <%= image_tag "no_prof_pic_present.jpg", class: "avatar-large-bordered" %>
    <% end %>
    <% end %>
  </div>
</div>

<div class="container">

  <div class="d-lg-flex justify-content-between">
    <div class="content-side">
      <div class="content-info" style="border-left: 2px solid #ABAAAA;">
        <div>
          <i class="far fa-circle icon-start-end" style="border-top: 3px solid white"></i>Start: <%= @trip.start_date %>
        </div>
        <% @steps.each do |step| %>
        <div id="step-<%= step.id %>">
          <div style="margin-top: 30px;">
            <%= render 'steps/partials/stepinfo', trip: @trip, step: step %>
          </div>
          <% step.activities.map do |activity| %>
          <div style="margin-top: 20px;">
            <%= render 'activities/partials/activityinfoshow', trip: @trip, step: step, activity: activity, user: @user %>
          </div>
          <% end %>
        </div>
        <% end %>
        <div style="margin-top: 30px;">
          <i class="far fa-circle icon-start-end" style="border-bottom: 5px solid white"></i>End: <%= @trip.end_date %>
        </div>
      </div>
    </div>

    <div class="map-side" style="margin-top: 50px;">
      <div id="map"></div>
    </div>
  </div>

  <script>
    function initMap() {
      var map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: <%= @trip.latitude %>, lng: <%= @trip.longitude %>},
        zoom: 5
      });
      <% @trip.steps.each do |step| %>
      var markerstep = new google.maps.Marker({
        position: {lat: <%= step.latitude %>, lng: <%= step.longitude %>},
        map: map
      })
      <% end %>
      <% activities_with_position = @trip.activities.select { |activity| activity.latitude.present? } %>
    <% activities_with_position.each do |activity| %>
      var markeractivity = new google.maps.Marker({
        position: {lat: <%= activity.latitude %>, lng: <%= activity.longitude %>},
        map: map
      })
    <% end %>
    }
    </script>
  </div>