config/routes.rb
Rails.application.routes.draw do
  # get 'activities/new'
  # get 'activities/create'
  # get 'activities/edit'
  # get 'activities/update'
  # get 'activities/save'
  # get 'activities/destroy'
  # get 'steps/new'
  # get 'steps/create'
  # get 'steps/edit'
  # get 'steps/save'
  # get 'steps/update'
  # get 'steps/destroy'

  devise_for :users
  root to: 'trips#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # resources trips:

    # resources :users, only: [ :show, :update ], param: :username
    get '/mytrips', to: 'pages#mytrips'
    get '/:username', to: 'users#show', as: :username
    post '/users/edit', to: 'users#update'

    resources :users, only: [ :update ]
    resources :trips do
      resources :steps, only: [ :new, :create, :edit, :update, :destroy ] do
        resources :activities, only: [ :new, :create, :edit, :update, :destroy ]
      end
    end
    get "profile", to: "profile#index"

    get '/testedittrip', to: 'pages#testedittrip'
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :trip
  has_many :activities, -> { order(position: :asc) }, dependent: :destroy
  acts_as_list scope: :trip

  # validates :nights, presence: true
  # validates :location, presence: true
  # validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def new
  end

    def create
      @step = Step.create(step_params)
      @step.trip_id = params["trip_id"].to_i
      @trip = Trip.find(@step.trip_id)
      @steps = @trip.steps.geocoded
      # @step.position = @steps.map {|step| step.position}.sort.last + 1
      @activity = Activity.new
      if @step.save
        redirect_to edit_trip_path(@trip)
      else
        render 'trips/edit'
      end
    end

    def edit
      @trip = Trip.find(params["trip_id"])
      @step = Step.find(params[:id])
    end

    def update
      @step = Step.find(params[:id])
      @trip = Trip.find(params["trip_id"].to_i)
      @step.update(step_params)
      #@step = Step.new(step_params)
      redirect_to edit_trip_path(@trip)

    end

    def destroy
      @step = Step.find(params[:id])
      @trip = Trip.find(params["trip_id"].to_i)
      @step.destroy
      redirect_to edit_trip_path(@trip)
    end

    private
    def step_params
      params["step"].permit(:location, :nights, :address, :latitude, :longitude)
    end
  end

app/views/steps/partials/_form.html.erb
<%= simple_form_for [@trip, step], html: {class: 'form-inline'} do |f| %>
  <%= f.input :location, placeholder: "Location", label: false %>
  <%= f.input :nights, placeholder: "Number of nights", label:false %>
  <%= f.submit "save", class: "btn btn-primary" %>
<% end %>

app/views/steps/partials/_stepadd.html.erb
<% if @steps.empty? %>
  <i class="fas fa-plus-circle icon-add-step"></i><a data-toggle="collapse" href="#collapseStepAdd" role="button" aria-expanded="false" aria-controls="collapseStepAdd" class="add-step-link">
    Add your first step
  </a>
<% else %>
  <i class="fas fa-plus-circle icon-add-step"></i><a data-toggle="collapse" href="#collapseStepAdd" role="button" aria-expanded="false" aria-controls="collapseStepAdd" class="add-step-link">
    Add new step
  </a>
<% end %>

<div class="collapse" id="collapseStepAdd">
  <div class="card card-body step-form" style="border: 0">

    <%= render 'steps/partials/stepaddinfo', trip: @trip, step: step %>

<!--
    <div class="loader-form-takeover">
     <div class="loader"></div>
    </div>
 -->
  </div>
</div>



<%#= f.input :location, label: false, placeholder: "Location" %>
<%#= ("<div id='geocoder' class='geocoder'></div>").html_safe %>
<%#= ("<div id='geocoder' class='geocoder'></div>").html_safe %>

app/views/steps/partials/_stepaddinfo.html.erb
<%= simple_form_for [@trip, step] do |f| %>
      <%= f.hidden_field :location, label: false, class: "step-location-input-js" %>
      <%= f.hidden_field :address, label: false, class: "step-address-input-js" %>
      <%= f.hidden_field :latitude %>
      <%= f.hidden_field :longitude %>
      <input type="text" class="form-control search-google" placeholder="Search...">
      <%= f.input :nights, placeholder: "Number of nights", label:false %>
      <%= f.submit "submit", class: "btn btn-secondary" %>


    <% end %>

app/views/steps/partials/_stepdelete.html.erb
<%= link_to ('<p style="margin-bottom: 0;padding-left: 15px; color: #ABAAAA; text-decoration: none; padding-bottom: 8px; ">Delete</p>').html_safe, trip_step_path(@trip, step),
      method: :delete,
      data: { confirm: "Are you sure?" } %>

app/views/steps/partials/_stepedit.html.erb
<a class="edit-delete-buttons" style="padding-left: 25px; color: #ABAAAA; padding-bottom: 8px;" data-toggle="collapse" href="#collapseEditStep<%= step.id %>" aria-expanded="false" aria-controls="collapseEditStep<%= step.id %>">
  Edit
</a>

app/views/steps/partials/_stepeditcollapse.html.erb
<div class="collapse" id="collapseEditStep<%= step.id %>">
        <div class="card card-body">
          <%= render 'steps/partials/stepadd', trip: @trip, step: step %>
        </div>
      </div>

app/views/steps/partials/_stepinfo.html.erb
<h3 class="step-info d-flex">
  <div class="icon-step-position">
  <%= step.position %>
  </div>
  <div style="color: #FE5665">

  <%= step.location %> - <% if step.nights != nil %><%= step.nights %> nights<% end %>

  <!-- <%# if step.nights != nil %>
    <%# if step.nights > 1 %><%#= step.nights %> nights
    <%# elsif step.nights <= 1 %><%#= step.nights %>night
    <%# end %>
  <%# end %>) -->

  </div>

</h3>



<!-- hey -->

<!--

<h3 class="step-info"><%= step.position %> . <%= step.location %>
    (<%# if step.nights > 1 %><%= step.nights %> nights<%# elsif step.nights <= 1 %><%= step.nights %>night<%# end %>)</h3> -->