config/routes.rb
Rails.application.routes.draw do
  # get 'activities/new'
  # get 'activities/create'
  # get 'activities/edit'
  # get 'activities/update'
  # get 'activities/save'
  # get 'activities/destroy'
  # get 'steps/new'
  # get 'steps/create'
  # get 'steps/edit'
  # get 'steps/save'
  # get 'steps/update'
  # get 'steps/destroy'

  devise_for :users
  root to: 'trips#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # resources trips:

    # resources :users, only: [ :show, :update ], param: :username
    get '/mytrips', to: 'pages#mytrips'
    get '/:username', to: 'users#show', as: :username
    post '/users/edit', to: 'users#update'

    resources :users, only: [ :update ]
    resources :trips do
      resources :steps, only: [ :new, :create, :edit, :update, :destroy ] do
        resources :activities, only: [ :new, :create, :edit, :update, :destroy ]
      end
    end
    get "profile", to: "profile#index"

    get '/testedittrip', to: 'pages#testedittrip'
end

app/views/pages/mytrips.html.erb
<% tripdraftcount = 0 %>
<% trippublishedcount = 0 %>
<% @trips.each do |trip| %>
<% if trip.published == false %>
<% tripdraftcount +=1 %>
<% elsif trip.published == true %>
<% trippublishedcount +=1 %>
<% end %>
<% end %>

<div class="container">
  <h2 style="margin-top: 60px;">My Trips</h2>
  <div id=draft-trips>
    <h4 style="margin-top: 20px; margin-bottom: 20px">Drafts (<%= tripdraftcount %>) </h4>
    <div class="row">
      <% @trips.each do |trip| %>
      <% if trip.published == false %>
      <div class="col-sm-12 col-md-6 col-lg-4">
        <div class="card-trip", style="position: relative">
          <div style="position: absolute; top: 8px; right: 10px;">
            <%= link_to ('<i class="far fa-edit icon-edit-delete"></i>').html_safe, edit_trip_path(trip) %>
            <%= link_to ('<i class="far fa-trash-alt icon-edit-delete"></i>').html_safe, trip_path(trip),
            method: :delete,
            class: 'btn btn-link',
              data: { confirm: "Are you sure?" } %>
            </div>
            <% if trip.photo.present?  %>
              <%= cl_image_tag trip.photo %>
             <% else  %>
              <img src="https://images.unsplash.com/photo-1488646953014-85cb44e25828?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3033&q=80" alt="">
            <% end %>

            <!-- <img src="https://images.unsplash.com/photo-1488646953014-85cb44e25828?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3033&q=80" alt=""> -->
            <div class="card-trip-infos">
              <div id='card-trip-title'>
                <strong><%= trip.name %></strong>
              </div>
              <div id='card-trip-location'>
                <p>
                <% array = [] %>
                <%  trip.steps.each do |step| %>
                <% array << step.location %>
                <% end %>
                <% if array.count == 0  %>
                <% elsif array.count == 1  %>
                <%=array[0]%>
                <% elsif array.count == 2  %>
                <%=array[0]%> <i class="fas fa-arrow-circle-right"></i> <%=array[1]%>
                <% elsif array.count == 3  %>
                <%=array[0]%> <i class="fas fa-arrow-circle-right"></i> <%=array[1]%> <i class="fas fa-arrow-circle-right"></i> <%=array[2]%>
                <% else %>
                <%=array[0]%> <i class="fas fa-arrow-circle-right"></i> <%=array[1]%> <i class="fas fa-arrow-circle-right"></i> ...<%= array.last %>
                <% end %>
              </p>
              </div>
              <div id='card-trip-day'>
                <%=(trip.end_date.to_date - trip.start_date.to_date).to_i%> days
              </div>
              <% @user = current_user %>
              <% if @user.photo.present? %>
              <%= cl_image_tag @user.photo, crop: :thumb, gravity: :face, class: "card-trip-user avatar-bordered" %>
              <% else %>
              <%= image_tag "no_prof_pic_present.jpg", class: "card-trip-user avatar-bordered" %>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>

        <!-- Add a new Draft button -->
        <div class="col-sm-12 col-md-6 col-lg-4">
          <div class="card-trip" style="background-color: #69DEC5; height: 300px; border-radius: 6px;">
            <div class="text-center" style="padding-top: 60px">
              <h1 style="color:white; font-size: 150px; font-weight: lighter;">+</h1>
            </div>
            <a href="" type="button" class="card-link" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-plus fa-3x" style="color: white; background-color: "></i></a>

            <%#= link_to , "google.fr" %>
            <%#= link_to ('<i class="fas fa-plus fa-4x"></i>').html_safe, trip_path(trip), class: 'card-link' %>

            <!-- Button trigger modal -->
        <!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
          Add a trip
        </button> -->
        <!-- Modal -->
        <% @trip = Trip.new %>
        <%= render "trips/partials/form", trip: @trip %>
        <!-- <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header trip-form">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">


                <!- end of Add new Draft button -->
              <!-- </div>
            </div>
          </div>
        </div> -->
      <!-- </div> -->
    </div>

  </div>
</div>

<div id=published-trips>
  <h4 style="margin-top: 20px; margin-bottom: 20px">Published (<%= trippublishedcount %>) </h4>
  <div class="row">
    <% @trips.each do |trip| %>
    <% if trip.published == true %>
    <div class="col-sm-12 col-md-6 col-lg-4">
      <div class="card-trip", style="position: relative">
        <div style="position: absolute; top: 8px; right: 10px;">
          <%= link_to ('<i class="far fa-edit icon-edit-delete"></i>').html_safe, edit_trip_path(trip) %>
          <%= link_to ('<i class="far fa-trash-alt icon-edit-delete"></i>').html_safe, trip_path(trip),
          method: :delete,
          class: 'btn btn-link',
            data: { confirm: "Are you sure?" } %>
            <%= link_to ('<i class="fas fa-link icon-edit-delete"></i>').html_safe, trip_path(trip) %>

          </div>
          <% if trip.photo.present?  %>
              <%= cl_image_tag trip.photo %>
             <% else  %>
              <img src="https://images.unsplash.com/photo-1488646953014-85cb44e25828?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3033&q=80" alt="">
            <% end %>
          <div class="card-trip-infos">
            <div id='card-trip-title'>
              <strong><%= trip.name %></strong>
            </div>
            <div id='card-trip-location'>
              <p>
                <% array = [] %>
                <%  trip.steps.each do |step| %>
                <% array << step.location %>
                <% end %>
                <% if array.count == 0  %>
                <% elsif array.count == 1  %>
                <%=array[0]%>
                <% elsif array.count == 2  %>
                <%=array[0]%> <i class="fas fa-arrow-circle-right"></i> <%=array[1]%>
                <% elsif array.count == 3  %>
                <%=array[0]%> <i class="fas fa-arrow-circle-right"></i> <%=array[1]%> <i class="fas fa-arrow-circle-right"></i> <%=array[2]%>
                <% else %>
                <%=array[0]%> <i class="fas fa-arrow-circle-right"></i> <%=array[1]%> <i class="fas fa-arrow-circle-right"></i> ...<%= array.last %>
                <% end %>
              </p>
            </div>
            <div id='card-trip-day'>
              <%=(trip.end_date.to_date - trip.start_date.to_date).to_i%> days
            </div>
            <% @user = current_user %>
            <% if @user.photo.present? %>
            <%= cl_image_tag @user.photo, crop: :thumb, gravity: :face, class: "card-trip-user avatar-bordered" %>
            <% else %>
            <%= image_tag "no_prof_pic_present.jpg", class: "card-trip-user avatar-bordered" %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>
</div>





<%#= link_to "More Details", trip_path(trip), class: 'card-link' %>
<%#= link_to "Edit Trip", edit_trip_path(trip), class: 'card-link' %>
        <%#= link_to "Delete Trip", trip_path(trip),
        method: :delete,
        data: { confirm: "Are you sure?" } %>