config/routes.rb
Rails.application.routes.draw do
  # get 'activities/new'
  # get 'activities/create'
  # get 'activities/edit'
  # get 'activities/update'
  # get 'activities/save'
  # get 'activities/destroy'
  # get 'steps/new'
  # get 'steps/create'
  # get 'steps/edit'
  # get 'steps/save'
  # get 'steps/update'
  # get 'steps/destroy'

  devise_for :users
  root to: 'trips#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # resources trips:

    # resources :users, only: [ :show, :update ], param: :username
    get '/mytrips', to: 'pages#mytrips'
    get '/:username', to: 'users#show', as: :username
    post '/users/edit', to: 'users#update'

    resources :users, only: [ :update ]
    resources :trips do
      resources :steps, only: [ :new, :create, :edit, :update, :destroy ] do
        resources :activities, only: [ :new, :create, :edit, :update, :destroy ]
      end
    end
    get "profile", to: "profile#index"

    get '/testedittrip', to: 'pages#testedittrip'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :step
  acts_as_list scope: :step
  # validates :name, presence: true

  # validates :description, length: { maximum: 500 }
  # validates :comment, length: { maximum: 500 }
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # reverse_geocoded_by :coordinates
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def create
    @activity = Activity.new(activity_params)
    @trip = params["trip_id"].to_i
    @activity.step_id = params["step_id"].to_i
    @activity.category = params["activity"]["category"]
    @activity.name = params["activity"]["name"]
    @activity.comment = params["activity"]["comment"]
    @step = Step.find(@activity.step_id)
    @activities = @step.activities
    # @activity.position = @activities.map {|activity| activity.position}.sort.last + 1
    # @step = Step.find(1)
    # @activity = Activity.new(activity_params)
    # @activity.step_id = @step
    # @trip = Trip.find(params["trip_id"])
    if @activity.save!
      redirect_to edit_trip_path(@trip)
    end
    # else
    #   render 'trips/edit'
    # end
  end

  def edit
    # @trip = Trip.find(params["trip_id"])
    # @step = Step.find(params["step_id"])
    # @activity = Activity.find(params[:id])
  end

  def update
    @trip = Trip.find(params["trip_id"].to_i)
    @step = Step.find(params["step_id"].to_i)
    @activity = Activity.find(params[:id])
    @activity.update(activity_params)
    redirect_to edit_trip_path(@trip)
  end

  def destroy
    @step = Step.find(params["step_id"].to_i)
    @activity = Activity.find(params[:id])
    @trip = Trip.find(params["trip_id"].to_i)
    @activity.destroy
    redirect_to edit_trip_path(@trip)
  end

  private
    def activity_params
      params["activity"].permit(:comment, :name, :rating, :url, :icon, :types, :address, :latitude, :longitude, :photo, :photo_google)
    end
  end

app/views/activities/partials/_activityadd.html.erb
    <!-- <h4 > -->
    <div class="d-flex">
      <i class="fas fa-plus-circle icon-add-activity"></i>
      <!-- <h4 style="color: #a09f9f; padding-right: 15px;">Add activity</h4> -->
      <div>
        <a href="" data-toggle="collapse" data-target="#multiCollapseSee-<%= step.id %>" role="button" aria-expanded="false" aria-controls="multiCollapseSee-<%= step.id %>" class="icon-activity-button-link"><i class="far fa-eye icon-activity-button"></i></a>
          <!-- <div class='inner'>
            Place
          </div></a> -->
        <a href="" data-toggle="collapse" data-target="#multiCollapseEat-<%= step.id %>" role="button" aria-expanded="false" aria-controls="multiCollapseEat-<%= step.id %>" class="icon-activity-button-link"><i class="fas fa-utensils icon-activity-button" style="padding: 5px 7px"></i></a>
          <!-- <div class='inner'>
            Restaurant
          </div></a> -->
        <a href="" data-toggle="collapse" data-target="#multiCollapseDrink-<%= step.id %>" role="button" aria-expanded="false" aria-controls="multiCollapseDrink-<%= step.id %>" class="icon-activity-button-link"><i class="fas fa-cocktail icon-activity-button"></i></a>
          <!-- <div class='inner'>
            Drinks
          </div></a> -->
        <a href="" data-toggle="collapse" data-target="#multiCollapseSleep-<%= step.id %>" role="button" aria-expanded="false" aria-controls="multiCollapseSleep-<%= step.id %>" class="icon-activity-button-link"><i class="fas fa-bed icon-activity-button"></i></a>
          <!-- <div class='inner'>
            Accommodation
          </div></a> -->
        <a href="" data-toggle="collapse" data-target="#multiCollapseMove-<%= step.id %>" role="button" aria-expanded="false" aria-controls="multiCollapseMove-<%= step.id %>" class="icon-activity-button-link"><i class="fas fa-bus icon-activity-button"></i></a>
          <!-- <div class='inner'>
            Transportation
          </div></a> -->
        <a href="" data-toggle="collapse" data-target="#multiCollapseComment-<%= step.id %>" role="button" aria-expanded="false" aria-controls="multiCollapseComment-<%= step.id %>" class="icon-activity-button-link"><i class="fas fa-comment icon-activity-button"></i></a>
          <!-- <div class='inner'>
            Comments
          </div></a> -->
      </div>
    </div>
    <div class="collapse multi-collapse" id="multiCollapseComment-<%= step.id %>" data-parent="#activitytypes-<%= step.id %>">
      <div class="card card-body" style="border: 0">
        <%= render 'activities/partials/formcomment', trip: @trip, step: step, activity: @activity %>
      </div>
    </div>

<div class="collapse multi-collapse" id="multiCollapseSleep-<%= step.id %>" data-parent="#activitytypes-<%= step.id %>">
      <div class="card card-body activity-form" style="border: 0">
        <%= render 'activities/partials/formsleep', trip: @trip, step: step, activity: @activity %>

 </div>
    </div>


    <div class="collapse multi-collapse" id="multiCollapseEat-<%= step.id %>" data-parent="#activitytypes-<%= step.id %>">
      <div class="card card-body activity-form" style="border: 0">
        <%= render 'activities/partials/formeat', trip: @trip, step: step, activity: @activity %>
      </div>
    </div>

    <div class="collapse multi-collapse" id="multiCollapseSee-<%= step.id %>" data-parent="#activitytypes-<%= step.id %>">
      <div class="card card-body activity-form" style="border: 0">
        <%= render 'activities/partials/formsee', trip: @trip, step: step, activity: @activity %>

      </div>
    </div>

<div class="collapse multi-collapse" id="multiCollapseDrink-<%= step.id %>" data-parent="#activitytypes-<%= step.id %>">
      <div class="card card-body activity-form" style="border: 0">

        <%= render 'activities/partials/formdrink', trip: @trip, step: step, activity: @activity %>


      </div>
    </div>

    <div class="collapse multi-collapse" id="multiCollapseMove-<%= step.id %>" data-parent="#activitytypes-<%= step.id %>">
      <div class="card card-body" style="border: 0">
        <%= render 'activities/partials/formmove', trip: @trip, step: step, activity: @activity %>
      </div>
    </div>

<!--
<script>
  $('.icon-activity-button-link').hover(function(){
    $('.inner').show();
},function(){
    $('.inner').hide();
});
</script>
 -->

<!--
<button class="btn btn-primary" data-toggle="collapse" data-target="#multiCollapseComment-<%= step.id %>" role="button" aria-expanded="false" aria-controls="multiCollapseComment-<%= step.id %>">Comment</i></button>
<button class="btn btn-primary" data-toggle="collapse" data-target="#multiCollapseSleep-<%= step.id %>" role="button" aria-expanded="false" aria-controls="multiCollapseSleep-<%= step.id %>">Sleep</button>
<button class="btn btn-primary" data-toggle="collapse" data-target="#multiCollapseEat-<%= step.id %>" role="button" aria-expanded="false" aria-controls="multiCollapseEat-<%= step.id %>">Eat</button>
<button class="btn btn-primary" data-toggle="collapse" data-target="#multiCollapseSee-<%= step.id %>" role="button" aria-expanded="false" aria-controls="multiCollapseSee-<%= step.id %>">See</button>
<button class="btn btn-primary" data-toggle="collapse" data-target="#multiCollapseDrink-<%= step.id %>" role="button" aria-expanded="false" aria-controls="multiCollapseDrink-<%= step.id %>">Drink</button>
<button class="btn btn-primary" data-toggle="collapse" data-target="#multiCollapseMove-<%= step.id %>" role="button" aria-expanded="false" aria-controls="multiCollapseMove-<%= step.id %>">Move</button>
 -->

app/views/activities/partials/_activitydelete.html.erb
<%= link_to ('<p style="margin-bottom: 0;padding-left: 15px; padding-bottom: 8px; color: #ABAAAA; text-decoration: none;">Delete</p>').html_safe, trip_step_activity_path(@trip, step, activity),
      method: :delete,
      data: { confirm: "Are you sure?" } %>

app/views/activities/partials/_activityedit.html.erb
<a class="edit-delete-buttons" style="padding-left: 25px; padding-bottom: 8px; color: #ABAAAA;" data-toggle="collapse" href="#collapseEditActivity<%= activity.id %>" role="button" aria-expanded="false" aria-controls="collapseEditActivity<%= activity.id %>">
  Edit
</a>

app/views/activities/partials/_activityeditcollapse.html.erb
<div class="collapse" id="collapseEditActivity<%= activity.id %>">
  <div class="card card-body">
    <% if activity.category == "Comment" %>
      <%= render 'activities/partials/formcomment', trip: @trip, step: step, activity: activity %>
    <% elsif activity.category == "Sleep" %>
      <%= render 'activities/partials/formsleep', trip: @trip, step: step, activity: activity %>
    <% elsif activity.category == "Eat" %>
      <%= render 'activities/partials/formeat', trip: @trip, step: step, activity: activity %>
    <% elsif activity.category == "See" %>
      <%= render 'activities/partials/formsee', trip: @trip, step: step, activity: activity %>
    <% elsif activity.category == "Drink" %>
      <%= render 'activities/partials/formsee', trip: @trip, step: step, activity: activity %>
    <% elsif activity.category == "Move" %>
      <%= render 'activities/partials/formmove', trip: @trip, step: step, activity: activity %>
    <% end %>

  </div>

</div>

app/views/activities/partials/_activitygeneralinformation.html.erb
  <div class="title d-flex">
    <div style="margin-top: 20px;">
      General information
    </div>
    <a data-toggle="collapse" href="#collapseExample<%= activity.id %>" role="button" aria-expanded="false" aria-controls="collapseExample<%= activity.id %>">
      <i class="fas fa-sort-down" style="color: black; margin-left: 8px; margin-top: 21px"></i>
    </a>
  </div>

<div class="collapse" id="collapseExample<%= activity.id %>">
  <div class="card card-body-general-information general-info-container" style="border: none;">
   <!--  <div class="d-flex">
      <i class="fas fa-tag"></i>
    -->
    <div class="pb-3">
      <% if activity.types.present? %>
      <% activity.types.split(",").each do |item| %>
      <%= "#" + item.gsub("_", "")%>
      <% end %>
      <% end %>
    </div>

    <div class="pb-3">
      <% unless activity.rating.nil? %>
      <%# total_stars = activity.rating.map { |review| review.stars }   %>
      <%# average_rating = total_stars.sum.to_i/total_stars.count %>
      <% counter = 0 %>
      <% 5.times do %>
      <i class="<%= activity.rating.to_i > counter ? 'fas fa-star' : 'far fa-star' %>"></i>
      <% counter += 1 %>
      <% end %>
      <% end %>
      <em>(Google Reviews)</em>
      <!-- (<%#= Review.count %> reviews) -->
    </div>
    <!-- </div> -->

    <!-- <div class="d-flex">
      <i class="fab fa-google"></i>
      <div> -->

      <!-- </div>
    </div>

    <div class="d-flex">
      <i class="fab fa-google"></i> -->
      <div class="pb-3">
        <strong>Address: </strong><%= activity.address %>
      </div>
   <!--  </div>

   -->

    <div class="url-content pb-2">
      <strong>Website: </strong>
     <%= link_to ('<i class="fas fa-external-link-alt"></i>').html_safe, activity.url, target: :blank, id: "visit-website-link" %>
   </div>




</div>
</div>

app/views/activities/partials/_activityinfo.html.erb
 <h4><% if activity.category == "See" %>
  <i class="far fa-eye icon-activity"></i>
<% elsif activity.category == "Eat" %>
  <i class="fas fa-utensils icon-activity"></i>
<% elsif activity.category == "Drink" %>
  <i class="fas fa-cocktail icon-activity"></i>
<% elsif activity.category == "Sleep" %>
  <i class="fas fa-bed icon-activity"></i>
<% elsif activity.category == "Move" %>
  <i class="fas fa-bus icon-activity"></i>
<% elsif activity.category == "Comment" %>
  <i class="fas fa-comment icon-activity"></i>
<% end %>
<%= activity.name %></h2>
<div>
  <%#= activity.comment %>
  <%#= activity.photo %>
  <%#= activity.types %>
  <%#= activity.rating %>
</div>
<%#= activity.position %>
<%#= activity.photo %>

app/views/activities/partials/_activityinfoedit.html.erb
 <div class="d-lg-flex" style="align-items: center">
   <h4><% if activity.category == "See" %>
    <i class="far fa-eye icon-activity"></i>
    <% elsif activity.category == "Eat" %>
    <i class="fas fa-utensils icon-activity"></i>
    <% elsif activity.category == "Drink" %>
    <i class="fas fa-cocktail icon-activity"></i>
    <% elsif activity.category == "Sleep" %>
    <i class="fas fa-bed icon-activity"></i>
    <% elsif activity.category == "Move" %>
    <i class="fas fa-bus icon-activity"></i>
    <% elsif activity.category == "Comment" %>
    <i class="fas fa-comment icon-activity"></i>
    <% end %>
    <%= activity.name %></h4>
    <div class="d-flex">
      <%= render 'activities/partials/activityedit', trip: @trip, step: step, activity: activity %>
      <%= render 'activities/partials/activitydelete', trip: @trip, step: step, activity: activity %>
    </div>
  </div>


<div class="collapse" id="collapseEditActivity<%= activity.id %>">
  <% if activity.category == "See" %>
    <div style="margin: 20px 0px 20px 25px;">
      <%= render 'activities/partials/formsee', trip: @trip, step: step, activity: activity %>
    </div>
  <% elsif activity.category == "Eat" %>
    <div style="margin: 20px 0px 20px 25px;">
      <%= render 'activities/partials/formeat', trip: @trip, step: step, activity: activity %>
    </div>
  <% elsif activity.category == "Drink" %>
    <div style="margin: 20px 0px 20px 25px;">
      <%= render 'activities/partials/formdrink', trip: @trip, step: step, activity: activity %>
    </div>
  <% elsif activity.category == "Sleep" %>
    <div style="margin: 20px 0px 20px 25px;">
      <%= render 'activities/partials/formsleep', trip: @trip, step: step, activity: activity %>
    </div>
  <% elsif activity.category == "Move" %>
    <div style="margin: 20px 0px 20px 25px;">
      <%= render 'activities/partials/formmove', trip: @trip, step: step, activity: activity %>
    </div>
  <% elsif activity.category == "Comment" %>
    <div style="margin: 20px 0px 20px 25px;">
      <%= render 'activities/partials/formcomment', trip: @trip, step: step, activity: activity %>
    </div>
  <% end %>
</div>


  <div>
    <% if activity.category == "See" || activity.category == "Eat" || activity.category == "Drink" || activity.category == "Sleep" %>
  <!-- <div class="address-fetched">
    <p> <strong>Address:</strong> <%= activity.address %> </p>
  </div> -->

  <div class="activity-information-container">
    <div class="d-md-flex photo-comment-container">
      <div class="photo-fetched-container">
        <%if activity.photo.present? %>
          <%= cl_image_tag activity.photo, width: 250, crop: :fill, class: "photo-fetched" %>
        <% else %>
          <img class="photo-fetched" src="<%= activity.photo_google %>" style="max-width: 400px" />
        <% end %>
      </div>
      <!-- GENERAL INFO ENDS FOR EAT SLEEP DRINK SEE -->

      <div class="comment-fetched-info-container mt-4 mt-md-0 ml-md-3">
        <div class="comment-container d-flex">
          <%# @user = @trip.user %>
          <%# @user = current_user %>

          <p><%= activity.comment %> </p>
        </div>
      </div>
    </div>
    </div>

    <% else %>

    <!-- <div class="comment-fetched-info-container"> -->
      <div class="comment-container-second d-flex" style="margin-left: 30px;">

        <p><%= activity.comment %> </p>
      </div>

      <!-- </div> -->

      <% end %>
    </div>

app/views/activities/partials/_activityinfoshow.html.erb
<h4><% if activity.category == "See" %>
  <i class="far fa-eye icon-activity"></i>
<% elsif activity.category == "Eat" %>
  <i class="fas fa-utensils icon-activity"></i>
<% elsif activity.category == "Drink" %>
  <i class="fas fa-cocktail icon-activity"></i>
<% elsif activity.category == "Sleep" %>
  <i class="fas fa-bed icon-activity"></i>
<% elsif activity.category == "Move" %>
  <i class="fas fa-bus icon-activity"></i>
<% elsif activity.category == "Comment" %>
  <i class="fas fa-comment icon-activity"></i>
<% end %>
<%= activity.name %></h4>
<div class="activity-information-container">
  <!-- ACTIVITY - SEE, EAT, DRINK, SLEEP -->
  <% if activity.category == "See" || activity.category == "Eat" || activity.category == "Drink" || activity.category == "Sleep" %>
  <!-- <div class="address-fetched">
    <p> <strong>Address:</strong> <%= activity.address %> </p>
  </div> -->

    <div class="d-md-flex ">
      <div class="photo-fetched-container">
        <%if activity.photo.present? %>
          <%= cl_image_tag activity.photo, width: 250, crop: :fill, class: "photo-fetched" %>
        <% else %>
          <img class="photo-fetched" src="<%= activity.photo_google %>" />
        <% end %>

      </div>
    <!-- GENERAL INFO ENDS FOR EAT SLEEP DRINK SEE -->

      <div class="comment-fetched-info-container mt-4 mt-md-0 ml-md-3">
        <div class="comment-container d-flex">
          <%# @user = @trip.user %>
          <%# @user = current_user %>
              <p><%= activity.comment %> </p>
        </div>
      </div>
      </div>
      <div class="general-info-fetched">
        <%= render 'activities/partials/activitygeneralinformation', trip: @trip, step: step, activity: activity, user: @user %>
      </div>


    <% else %>

      <!-- <div class="comment-fetched-info-container"> -->
        <div class="comment-container-second d-flex">

              <p><%= activity.comment %> </p>
        </div>

      <!-- </div> -->

    <% end %>

</div>

app/views/activities/partials/_formcomment.html.erb
<%= simple_form_for [@trip, step, activity] do |f| %>
  <h4 style="padding-bottom: 10px">Any comments/tips</h4>
  <%= f.hidden_field :category, value: "Comment" %>
  <%= f.hidden_field :name, value: "General comments" %>
  <%= f.input :comment, placeholder: "Enter comment", label:false %>
  <%= f.submit "submit", class: "btn btn-secondary" %>
<% end %>

app/views/activities/partials/_formdrink.html.erb
<%= simple_form_for [@trip, step, activity] do |f| %>

<h4 style="padding-bottom: 10px">Where to drink</h4>
<%= f.hidden_field :category, value: "Drink" %>
<%= f.hidden_field :rating, class: "activity-rating-input-js" %>
<%= f.hidden_field :url, class: "activity-url-input-js" %>
<%= f.hidden_field :icon, class: "activity-icon-input-js" %>
<%= f.hidden_field :types, class: "activity-types-input-js" %>
<%= f.hidden_field :name, class: "activity-name-input-js"  %>
<%= f.hidden_field :address, class: "activity-address-input-js" %>
<%= f.hidden_field :photo_google, class: "activity-photo-input-js" %>
<%= f.hidden_field :latitude, class: "activity-latitude-input-js" %>
<%= f.hidden_field :longitude, class: "activity-longitude-input-js" %>
<input type="text" class="form-control search-google" style="position: relative" placeholder="Search...">
<%= f.input :comment, placeholder: "Share your feedback", label: false %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.submit "submit", class: "btn btn-secondary" %>
<% end %>



<!-- <input type="hidden" name="" class="activity-photo-input-js" /> -->

<%#= ("<div id='geocoder' class='geocoder form-drink'></div>").html_safe %>

app/views/activities/partials/_formeat.html.erb
<%= simple_form_for [@trip, step, activity] do |f| %>
  <h4 style="padding-bottom: 10px">Where to eat</h4>
  <%= f.hidden_field :category, value: "Eat" %>
  <%#= f.input :name, placeholder: "Location", label: false %>

  <%= f.hidden_field :name, label: false, class: "activity-name-input-js" %>

  <%= f.hidden_field :rating, class: "activity-rating-input-js" %>
  <%= f.hidden_field :url, class: "activity-url-input-js" %>
  <%= f.hidden_field :icon, class: "activity-icon-input-js" %>
  <%= f.hidden_field :types, class: "activity-types-input-js" %>
  <%= f.hidden_field :address, class: "activity-address-input-js" %>
  <%= f.hidden_field :photo_google, class: "activity-photo-input-js" %>
  <%= f.hidden_field :latitude, class: "activity-latitude-input-js" %>
  <%= f.hidden_field :longitude, class: "activity-longitude-input-js" %>
  <input type="text" class="form-control search-google" placeholder="Search...">
  <%= f.input :comment, placeholder: "Share your feedback", label: false %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "submit", class: "btn btn-secondary" %>
<% end %>




<%#= ("<div id='geocoder' class='geocoder'></div>").html_safe %>

app/views/activities/partials/_formmove.html.erb
<%= simple_form_for [@trip, step, activity] do |f| %>
  <h4 style="padding-bottom: 10px">How to get there?</h4>
  <%= f.hidden_field :category, value: "Move" %>
  <%= f.input :name, collection: ["Plane", "Taxi", "Ferry", "Train", "Bus"], label: false, placeholder: "Select type of transport" %>
  <%= f.input :comment, placeholder: "Share your feedback", label: false %>
  <%= f.submit "submit", class: "btn btn-secondary" %>
<% end %>

app/views/activities/partials/_formsee.html.erb
<%= simple_form_for [@trip, step, activity] do |f| %>
  <h4 style="padding-bottom: 10px">What to visit</h4>
  <%= f.hidden_field :category, value: "See" %>
  <%= f.hidden_field :name, label: false, class: "activity-name-input-js" %>
  <%= f.hidden_field :rating, class: "activity-rating-input-js" %>
  <%= f.hidden_field :url, class: "activity-url-input-js" %>
  <%= f.hidden_field :icon, class: "activity-icon-input-js" %>
  <%= f.hidden_field :types, class: "activity-types-input-js" %>
  <%= f.hidden_field :address, class: "activity-address-input-js" %>
  <%= f.hidden_field :photo_google, class: "activity-photo-input-js" %>
  <%= f.hidden_field :latitude, class: "activity-latitude-input-js" %>
  <%= f.hidden_field :longitude, class: "activity-longitude-input-js" %>
  <input type="text" class="form-control search-google" placeholder="Search...">
  <%= f.input :comment, placeholder: "Share your feedback", label: false %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "submit", class: "btn btn-secondary" %>
<% end %>


<%#= ("<div id='geocoder' class='geocoder'></div>").html_safe %>
<!-- <div class="mapbox-class">

  </div> -->

app/views/activities/partials/_formsleep.html.erb
        <%= simple_form_for [@trip, step, activity] do |f| %>
          <h4 style="padding-bottom: 10px">Where to sleep</h4>
          <%= f.hidden_field :category, value: "Sleep" %>
          <%= f.hidden_field :rating, class: "activity-rating-input-js" %>
          <%= f.hidden_field :url, class: "activity-url-input-js" %>
          <%= f.hidden_field :icon, class: "activity-icon-input-js" %>
          <%= f.hidden_field :types, class: "activity-types-input-js" %>
          <%= f.hidden_field :address, class: "activity-address-input-js" %>
          <%= f.hidden_field :name, label: false, class: "activity-name-input-js" %>
          <%= f.hidden_field :photo_google, class: "activity-photo-input-js" %>
          <%= f.hidden_field :latitude, class: "activity-latitude-input-js" %>
          <%= f.hidden_field :longitude, class: "activity-longitude-input-js" %>
          <input type="text" class="form-control search-google" placeholder="Search...">
          <%= f.input :comment, placeholder: "Share your feedback", label: false %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.submit "submit", class: "btn btn-secondary" %>
        <% end %>


<%#= ("<div id='geocoder' class='geocoder'></div>").html_safe %>